version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: lambda,apigateway,iam,logs
      DEBUG: 1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"